name: Project Item Template
description: 'Issue used for non code related tickets : Project Items '
title: "[Item]: "
labels: ["Project"]
assignees:
  - justrebl

body: 
  - type: textarea
    id: what-needs-to-happen
    attributes:
      label: What needs to happen?
      description: Please detail as much as possible the steps you want to take to complete this item.
      placeholder: ex. I want to create a new project item template as follows
      value: Here is what need to happen.
  - type: input
    id: external-source
    attributes:
      label : External Source
      description : Any External source that can help to add more context to the issue
      placeholder : ex. https://www.github.com